name: native_toast
description: The Flutter Plugin to show native toast on Android
version: 0.0.2
homepage: https://github.com/imihirpaldhikar/native_toast

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.imihirpaldhikar.native_toast
        pluginClass: NativeToastPlugin